apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - {{ ingress }}
  env:
    - name: APIGW_URL
      value: {{ env.apigw.url }}
    - name: BRUKERNOTIFIKASJON_PAA
      value: "{{ env.brukernotifikasjon.paa }}"
    - name: DISCOVERY_URL
      value: {{ env.azure.discovery-url }}
    - name: AUD_FP
      value: {{ env.azure.audience }}
    - name: VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID
      value: "{{env.tls.virksomhetssertifikat.prosjekt-id}}"
    - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_NAVN
      value: {{ env.tls.virksomhetssertifikat.hemmelighet-navn }}
    - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_VERSJON
      value: "{{env.tls.virksomhetssertifikat.hemmelighet-versjon}}"
    - name: ESIGNERING_SUKSESS_URL
      value: {{ env.posten-esignering.suksess-url }}
    - name: ESIGNERING_AVBRUTT_URL
      value: {{ env.posten-esignering.avbrutt-url }}
    - name: ESIGNERING_FEILET_URL
      value: {{ env.posten-esignering.feilet-url }}
    - name: FARSKAPSPORTAL_URL
      value: {{ env.farskapsportal.url }}
    - name: INTEGRATION_TEST_CONTROLLER_PAA
      value: "{{env.integration-test-controller.paa}}"
    - name: KAFKA_BROKERS
      value: {{ env.kafka.brokers }}
    - name: KAFKA_SCHEMA_REGISTRY_URL_CONFIG
      value: {{ env.kafka.schema-registry.url }}
    - name: SKATT_URL
      value: {{ env.skatt.url }}
  envFrom:
    - secret: farskapsportal-api-secret
    - configmap: loginservice-idporten
  gcp:
    sqlInstances:
      - name: {{ env.gcp.sql-instances.name }}
        tier: {{ env.gcp.sql-instances.tier }}
        type: {{ env.gcp.sql-instances.type }}
        databases:
          - name: {{ env.gcp.sql-instances.databases.name }}
            envVarPrefix: {{ env.gcp.sql-instances.databases.env-var-prefix }}
  accessPolicy:
    outbound:
      external:
        - host: api.difitest.signering.posten.no
        - host: folkeregisteret-api-ekstern.sits.no
        - host: secretmanager.googleapis.com
        - host: kafka-schema-registry.nais-q.adeo.no
