apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - {{ ingress }}
  env:
    - name: APIGW_URL
      value: https://api-gw-q1.oera.no
    - name: BRUKERNOTIFIKASJON_PAA
      value: "true"
    - name: DISCOVERY_URL
      value: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    - name: AUD_FP
      value: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
    - name: VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID
      value: "719909854975"
    - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_NAVN
      value: test-virksomhetssertifikat-felles-keystore-jceks_2018-2021
    - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_VERSJON
      value: "3"
    - name: ESIGNERING_SUKSESS_URL
      value: https://farskapsportal-feature.dev.nav.no/suksess
    - name: ESIGNERING_AVBRUTT_URL
      value: https://farskapsportal-feature.dev.nav.no/avbrutt
    - name: ESIGNERING_FEILET_URL
      value: https://farskapsportal-feature.dev.nav.no/feilet
    - name: FARSKAPSPORTAL_URL
      value: https://farskapsportal-feature.dev.nav.no
    - name: INTEGRATION_TEST_CONTROLLER_PAA
      value: "true"
    - name: KAFKA_BROKERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL_CONFIG
      value: https://kafka-schema-registry.nais-q.adeo.no
    - name: SKATT_URL
      value: https://folkeregisteret-api-ekstern.sits.no
  envFrom:
    - secret: farskapsportal-api-secret
    - configmap: loginservice-idporten
  gcp:
    sqlInstances:
      - name: {{ env.gcp.sql-instances.name }}
        tier: {{ env.gcp.sql-instances.tier }}
        type: {{ env.gcp.sql-instances.type }}
        databases:
          - name: {{ env.gcp.sql-instances.databases.name }}
            envVarPrefix: {{ env.gcp.sql-instances.databases.env-var-prefix }}
  accessPolicy:
    outbound:
      external:
        - host: {{ env.posten-esignering.host }}
        - host: {{ env.skatt.host }}
        - host: {{ env.gcp.secretmanager.host }}
        - host: {{ env.kafka.schema-registry.host }}
