apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: farskapsportal-api
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 35
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 30
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress_preprod }}
    - {{ ingress_nais }}
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: farskapsportal