apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - {{ ingress }}
  env:
  { { #each env}}
      - name: {{this.name } }
  value: "{{this.value}}"
  {{/each}}


  env:
    - name: APIGW_URL
      value: {{ apigw.url }}
    - name: BRUKERNOTIFIKASJON_PAA
      value: "{{ brukernotifikasjon.paa }}"
    - name: DISCOVERY_URL
      value: {{ azure.discovery-url }}
    - name: AUD_FP
      value: {{ azure.audience }}
    - name: VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID
      value: "{{ tls.virksomhetssertifikat.prosjekt-id }}"
    - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_NAVN
      value: {{ tls.virksomhetssertifikat.hemmelighet-navn }}
    - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_VERSJON
      value: "{{ tls.virksomhetssertifikat.hemmelighet-versjon }}"
    - name: ESIGNERING_SUKSESS_URL
      value: {{ posten.esignering.suksess-url }}
    - name: ESIGNERING_AVBRUTT_URL
      value: {{ posten.esignering.avbrutt-url }}
    - name: ESIGNERING_FEILET_URL
      value: {{ posten.esignering.feilet-url }}
    - name: FARSKAPSPORTAL_URL
      value: {{ farskapsportal.url }}
    - name: INTEGRATION_TEST_CONTROLLER_PAA
      value: "{{ integration-test-controller.paa }}"
    - name: KAFKA_BROKERS
      value: {{ kafka.brokers }}
    - name: KAFKA_SCHEMA_REGISTRY_URL_CONFIG
      value: {{ kafka.schema-registry.url }}
    - name: SKATT_URL
      value: {{ skatt.url }}
  envFrom:
    - secret: farskapsportal-api-secret
    - configmap: loginservice-idporten
  gcp:
    sqlInstances:
      - name: {{ gcp.sql-instances.name }}
        tier: {{ gcp.sql-instances.tier }}
        type: {{ gcp.sql-instances.type }}
        databases:
          - name: {{ gcp.sql-instances.databases.name }}
            envVarPrefix: {{ gcp.sql-instances.databases.env-var-prefix }}
  accessPolicy:
    outbound:
      external:
        - host: api.difitest.signering.posten.no
        - host: {{ skatt.host }}
        - host: {{ gcp.secretmanager.host }}
        - host: {{ kafka.schema-registry.host }}
