apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      allowAllUsers: true
      enabled: true
  tokenx:
    enabled: true
  image: {{ image }}
  kafka:
    pool: nav-dev
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    max: {{ replicas }}
    min: {{ replicas }}
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  secureLogs:
    enabled: true
  ingresses:
    - {{ ingress }}
  env:
    - name: APPNAVN
      value: {{ name }}
    - name: SPRING_PROFILES_ACTIVE
      value: live, nais
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - name: fp-feature
        tier: db-f1-micro
        type: POSTGRES_15
        databases:
          - name: fpdb-feature
            envVarPrefix: DB
      - name: fp-feature-15
        tier: db-f1-micro
        type: POSTGRES_15
        databases:
          - name: fpdb-feature-15
            envVarPrefix: DB_15

  accessPolicy:
    inbound:
      rules:
        - application: farskapsportal-ui
        - application: farskapsportal-ui-feature
        - application: statuspoll
          namespace: navdig
          cluster: dev-gcp
    outbound:
      external:
        - host: api.difitest.signering.posten.no
        - host: folkeregisteret-api-ekstern.sits.no
        - host: secretmanager.googleapis.com
        - host: oppgave.dev-fss-pub.nais.io
  webproxy: true
