name: farskapsportal-api
ingress: https://farskapsportal-api.intern.nav.no
gcp:
  secretmanager.host: secretmanager.googleapis.com
  sql-instances:
    diskSize: 505
    name: fp-prod
    tier: db-custom-1-3840
    type: POSTGRES_12
    databases:
      name: fpdb-prod
      env-var-prefix: DB
      users:
        asynkron:
          name: asynkron_prod
env:
  - name: APIGW_URL
    value: https://api-gw.oera.no
  - name: BRUKERNOTIFIKASJON_PAA
    value: "true"
  - name: DB_USER_ASYNKRON
    value: asynkron_prod
  - name: POSTGRES_CONNECTION_NAME
    value: farskapsportal-prod-f231:europe-north1:fp-prod
  - name: VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID
    value: "642182003125"
  - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_NAVN
    value: virksomhetssertifikat-farskap-keystore-jceks_2021-2024
  - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_VERSJON
    value: "3"
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_PROSJEKT_ID
    value: "642182003125"
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_HEMMELIGHET_NAVN
    value: farskap-keystore-credentials-json
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_HEMMELIGHET_VERSJON
    value: "3"
  - name: ESIGNERING_SUKSESS_URL
    value: https://farskapsportal.nav.no/suksess
  - name: ESIGNERING_AVBRUTT_URL
    value: https://farskapsportal.nav.no/avbrutt
  - name: ESIGNERING_FEILET_URL
    value: https://farskapsportal.nav.no/avbrutt
  - name: FARSKAPSPORTAL_URL
    value: https://farskapsportal.nav.no
  - name: INTEGRATION_TEST_CONTROLLER_PAA
    value: "false"
  - name: SKATT_URL
    value: https://folkeregisteret.api.skatteetaten.no
# Fra gammel asynkron app
  - name: ARKIVERINGSINTERVALL
    value: 900000
  - name: ARKIVERINGSFORSINKELSE
    value: 60000
  - name: DEAKTIVERE_OVERSENDTE_ERKLAERINGER_ETTER_ANTALL_DAGER
    value: 30
  - name: DEAKTIVERINGSRATE
    value: "0 30 13 * * ?"
  - name: DOKUMENTSLETTINGSRATE
    value: "0 30 2 * * ?"
  - name: OPPGAVEAPI_URL
    value: https://oppgave.prod-fss-pub.nais.io
  - name: OPPGAVE_SCOPE
    value: prod-fss.oppgavehandtering.oppgave
  - name: SKATT_URL
    value: https://folkeregisteret.api.skatteetaten.no
  - name: OPPGAVESTYRINGSINTERVALL
    value: "0 0 7 * * ?"
  - name: OPPGAVESTYRINGSFORSINKELSE
    value: 1
  - name: VARSLE_OM_UFERDIG_ERKLAERING_CRON
    value: "0 0 14 ? * TUE"
  - name: VURDERE_OPPGAVE_INTERVALL
    value: "0 0 7 ? * 1-5"
secret:
  - name: farskapsportal-api-secret
