spring.devtools.add-properties: false

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator
  endpoint.health.show-details: always

urls:
  pdl-api:
    base-url: ${PDL_API_BASE_URL}
    graphql-endpoint: "/graphql"
  sts:
    base-url: ${STS_BASE_URL}
    security-token-service-endpoint: "/rest/v1/sts/token"

farskapsportal-api.servicebruker.brukernavn: srvfarskapsportal
farskapsportal-api.servicebruker.passord: ${SRVFARSKAPSPORTAL_PWD}

---
spring.profiles: live

no.nav:
  security.jwt.issuer.selvbetjening:
    discoveryurl: ${DISCOVERY_URL}
    accepted_audience: ${AUD_FP}

---
spring.profiles: test, local, integration-test

no.nav.security.jwt:
  issuer.selvbetjening :
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

---
########## Mock props ##########
spring.profiles: test, local

STUB_URL: http://localhost:8096
STS_BASE_URL: ${STUB_URL}
PDL_API_BASE_URL: ${STUB_URL}
APIKEY_PDLAPI_FP: keyForZoneCrossing
APIKEY_STS_FP: keyForZoneCrossing

farskapsportal-api.servicebruker.brukernavn: se-vault
farskapsportal-api.servicebruker.passord: se-vault

