no.nav.security.jwt:
  issuer.isso:
    discoveryurl: https://login.microsoftonline.com/NAVQ.onmicrosoft.com/.well-known/openid-configuration
    accepted_audience: 38e07d31-659d-4595-939a-f18dce3446c5
    cookiename: isso-idtoken
    proxyurl: http://webproxy.nais:8088