spring.devtools.add-properties: false

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator
  endpoint.health.show-details: always

urls:
  apigw: ${APIGW_URL}
  pdl-api:
    graphql-endpoint: "/rest/v1/sts/token"
  sts:
    security-token-service-endpoint: "/graphql"

farskapsportal-api.servicebruker.brukernavn: srvfarskapsportal
farskapsportal-api.servicebruker.passord: ${SRVFARSKAPSPORTAL_PWD}

---
spring.profiles: live

no.nav.security.jwt:
  issuer.isso:
    discoveryurl: https://login.microsoftonline.com/NAVQ.onmicrosoft.com/.well-known/openid-configuration
    accepted_audience: ${AUD_FP}
    cookiename: isso-idtoken
    proxyurl: http://webproxy.nais:8088

---
########## Mock props ##########
spring.profiles: test, local

APIGW_URL: http://localhost:8096
APIKEY_PDLAPI_FP: keyForZoneCrossing
APIKEY_STS_FP: keyForZoneCrossing

no.nav.security.jwt:
  issuers: isso
  issuer.isso:
    discoveryurl: http://metadata
    acceptedaudience: aud-localhost
    cookie_name: localhost-idtoken

farskapsportal-api.servicebruker.brukernavn: se-vault
farskapsportal-api.servicebruker.passord: se-vault

