spring.devtools.add-properties: false

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator
  endpoint.health.show-details: always

url:
  pdl-api:
    base-url: ${APIGW_URL}
    graphql-endpoint: "/pdl-api/graphql"
  sts:
    base-url: ${APIGW_URL}
    security-token-service-endpoint: "/security-token-service/rest/v1/sts/token"

farskapsportal-api:
  servicebruker.brukernavn: srvfarskapsportal
  servicebruker.passord: ${SRVFARSKAPSPORTAL_PWD}
  disable-esignering: true

---
spring.profiles: live

no.nav:
  security.jwt.issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?user=${DB_USERNAME}&password=${DB_PASSWORD}
    hikari:
      idle-timeout: 10001
      max-lifetime: 30001
      connectionTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
  flyway:
    enabled: false
    locations: classpath:/db/migration
  jpa.hibernate:
    connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider

---
spring:
  profiles: test
  flyway.enabled: false
# Lar wiremock håndtere esignering
farskapsportal-api.disable-esignering: false

---
########## Mock props ##########
spring.profiles: test, local

WIREMOCK_URL: http://localhost:8096
APIKEY_PDLAPI_FP: keyForZoneCrossing
APIKEY_STS_FP: keyForZoneCrossing

url:
  pdl-api.base-url: ${WIREMOCK_URL}
  sts.base-url: ${WIREMOCK_URL}
  esignering: ${WIREMOCK_URL}

no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

farskapsportal-api.servicebruker.brukernavn: se-vault
farskapsportal-api.servicebruker.passord: se-vault

### H2 config ###
spring:
  flyway.enabled: false
  datasource.type: com.zaxxer.hikari.HikariDataSource
  datasource.url: jdbc:h2:mem:default
  h2.console.enabled: true
  jpa.hibernate.hbmddl-auto: create-drop

---
spring:
  profiles: local

# Lokal profil bruker selvstendige wiremocks
wiremock.server:
  files: classpath:/__files
  stubs: classpath:/stubs

---
spring:
  profiles: local-postgres
  # Oppsett for flyway med hikari og postgres
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    password: local
    databaseName: postgres
    portNumber: 5432
    serverName: localhost
    hikari:
      idle-timeout: 10001
      max-lifetime: 30001
      connectionTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
  flyway:
    enabled: false
    flyway.locations: classpath:/db/migration
  jpa.hibernate:
    connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider

WIREMOCK_URL: http://localhost:8096
APIKEY_PDLAPI_FP: keyForZoneCrossing
APIKEY_STS_FP: keyForZoneCrossing

url:
  pdl-api.base-url: ${WIREMOCK_URL}
  sts.base-url: ${WIREMOCK_URL}
  esignering: ${WIREMOCK_URL}

no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

farskapsportal-api:
  servicebruker.brukernavn: se-vault
  servicebruker.passord: se-vault

wiremock.server:
  files: classpath:/__files
  stubs: classpath:/stubs

farskapsportal-api.disable-esignering: false

---

spring.profiles: integration-test

no.nav:
  security.jwt.issuer.selvbetjening:
    discoveryurl: https://navtestb2c.b2clogin.com/navtestb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5

url:
  pdl-api:
    base-url: https://api-gw-q1.oera.no
  sts:
    base-url: https://api-gw-q1.oera.no
