spring:
  devtools.add-properties: false
  main.allow-bean-definition-overriding: true

consumer.skatt:
  maks-antall-forbindelser: 5
  maks-antall-forbindelser-per-rute: 5
  maks-ventetid-lesing: 10000
  maks-ventetid-forbindelse: 10000

farskapsportal.egenskaper:
  min-antall-uker-til-termindato: -3
  maks-antall-uker-til-termindato: 21
  maks-antall-maaneder-etter-foedsel: 3
  nav.orgnummer: 889640782
  kontroll.far:
    forsoek-fornyes-etter-antall-dager: 1
    maks-antall-forsoek: 5
  posten.esignering:
    suksess-url: ${ESIGNERING_SUKSESS_URL}
    avbrutt-url: ${ESIGNERING_AVBRUTT_URL}
    feilet-url: ${ESIGNERING_FEILET_URL}
  skatt:
    intervall.overfoering: 3600000

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator
  endpoint.health.show-details: always

url:
  pdl-api:
    base-url: ${APIGW_URL}
    graphql: "/pdl-api/graphql"
  sts:
    base-url: ${APIGW_URL}
    security-token-service: "/security-token-service/rest/v1/sts/token"
  skatt:
    base-url: ${SKATT_URL}
    registrering-av-farskap: "/folkeregisteret/mottak/api/registrering_av_farskap_v1"

farskapsportal-api:
  servicebruker.brukernavn: srvfarskapsportal
  servicebruker.passord: ${SRVFARSKAPSPORTAL_PWD}
  disable-esignering: false

---
spring:
  cloud.gcp.secretmanager.project-id: ${VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID}
  config.activate.on-profile: live
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?user=${DB_USERNAME}&password=${DB_PASSWORD}
    hikari:
      idle-timeout: 10001
      max-lifetime: 30001
      connectionTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
  flyway:
    enabled: false
    locations: classpath:/db/migration
  jpa:
    hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    database: postgresql

no.nav:
  security.jwt.issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}

---
spring:
  config.activate.on-profile: test, local, integration-test, scheduled-test, skatt-ssl-test
  flyway.enabled: false
  datasource.type: com.zaxxer.hikari.HikariDataSource
  datasource.url: jdbc:h2:mem:default
  h2.console.enabled: true
  jpa.hibernate.hbmddl-auto: create-drop

########## Mock props ##########
SKATT_STUB_HOST: http://localhost:8080
WIREMOCK_URL: http://localhost:8096
APIKEY_PDLAPI_FP: keyForZoneCrossing
APIKEY_STS_FP: keyForZoneCrossing

url:
  pdl-api.base-url: ${WIREMOCK_URL}
  sts.base-url: ${WIREMOCK_URL}
  skatt.base-url: ${SKATT_STUB_HOST}

farskapsportal-api.servicebruker.brukernavn: se-vault
farskapsportal-api.servicebruker.passord: se-vault

---
spring:
  config.activate.on-profile: local, test, local-postgres, remote-postgres, integration-test, scheduled-test, skatt-ssl-test
  flyway.enabled: false

local.server.port: 8080

ESIGNERING_SUKSESS_URL: "http://localhost:8080/all-good"
ESIGNERING_AVBRUTT_URL: "http://localhost:8080/f.this"
ESIGNERING_FEILET_URL: "http://localhost:8080/damn"
INTEGRATION_TEST_CONTROLLER_PAA: true

no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

# Lar wiremock håndtere esignering
farskapsportal-api.disable-esignering: false

posten_esignering_suksess_url: https://localhost:8080/api/v1/farskapsportal/farskapserklaering/redirect,
posten_esignering_avbrutt_url: https://localhost:8080/api/v1/farskapsportal/farskapserklaering/signering/avbrutt,
posten_esignering_feilet_url: https://localhost:8080/api/v1/farskapsportal/farskapserklaering/signering/feilet

url.esignering: ${WIREMOCK_URL}

---

spring.config.activate.on-profile: local

# Lokal profil bruker selvstendige wiremocks
wiremock.server:
  files: classpath:/__files
  stubs: classpath:/stubs

---
spring:
  config.activate.on-profile: local-postgres, remote-postgres
  # Oppsett for flyway med hikari og postgres
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    password:
    databaseName: postgres
    portNumber: 5432
    serverName: localhost
    hikari:
      idle-timeout: 10001
      max-lifetime: 30001
      connectionTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
  flyway:
    enabled: false
    flyway.locations: classpath:/db/migration
  jpa:
    hibernate:
      connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider

WIREMOCK_URL: http://localhost:8096
APIKEY_PDLAPI_FP: keyForZoneCrossing
APIKEY_STS_FP: keyForZoneCrossing

url:
  pdl-api.base-url: ${WIREMOCK_URL}
  sts.base-url: ${WIREMOCK_URL}
  skatt.base-url: ${WIREMOCK_URL}

farskapsportal-api:
  servicebruker.brukernavn: se-vault
  servicebruker.passord: se-vault

wiremock.server:
  files: classpath:/__files
  stubs: classpath:/stubs

---
spring:
  config.activate.on-profile: remote-postgres
  datasource:
    username: ${REMOTE_POSTGRES_USER}
    url: jdbc:postgresql://localhost:5432/farskapsportaldb-feature
    password: ${REMOTE_POSTGRES_PWD}
    databaseName: farskapsportaldb-feature



---
spring.config.activate.on-profile: scheduled-test
farskapsportal.egenskaper.skatt.intervall.overfoering: 3000

---
spring.config.activate.on-profile: skatt-ssl-test

# SSL-oppsett med selfsigned server og klient-sertifikat for SkattStubController.
# Brukes av SkattConsumerSslTest.
server:
  port: 9002
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:server-selfsigned.jks
    key-store-password: qwer1234
    key-alias: nt-ms
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:server-selfsigned.jks
    trust-store-password: qwer1234
    turst-store-type: JKS

sertifikat:
  passord: qwer1234
  keystore-type: jks
  keystore-name: client-selfsigned.jks


---
spring.config.activate.on-profile: integration-test

farskapsportal.egenskaper:
  skatt:
    intervall.overfoering: 3600000

url:
  skatt.base-url: https://folkeregisteret-api-ekstern.sits.no
  esignering: https://api.difitest.signering.posten.no/api

sertifikat:
  passord: ${KEYSTORE_PASSWORD}
  keystore-type: jceks
  keystore-name: test_VS_decrypt_2018-2021.jceks

---

spring.config.activate.on-profile: integration-test2

no.nav:
  security.jwt.issuer.selvbetjening:
    discoveryurl: https://navtestb2c.b2clogin.com/navtestb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5

url:
  pdl-api:
    base-url: https://api-gw-q1.oera.no
  sts:
    base-url: https://api-gw-q1.oera.no
