spring.devtools.add-properties: false

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator
  endpoint.health.show-details: always

urls:
  pdl-api:
    base-url: ${APIGW_URL}
    graphql-endpoint: "/graphql"
  sts:
    base-url: ${APIGW_URL}
    security-token-service-endpoint: "/rest/v1/sts/token"

farskapsportal-api.servicebruker.brukernavn: srvfarskapsportal
farskapsportal-api.servicebruker.passord: ${SRVFARSKAPSPORTAL_PWD}

---
spring.profiles: live

no.nav:
  security.jwt.issuer.selvbetjening:
    discoveryurl: ${DISCOVERY_URL}
    accepted_audience: ${AUD_FP}

---
########## Mock props ##########
spring.profiles: test, local

APIGW_URL: http://localhost:8096
APIKEY_PDLAPI_FP: keyForZoneCrossing
APIKEY_STS_FP: keyForZoneCrossing

no.nav.security.jwt:
  issuer.selvbetjening :
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

farskapsportal-api.servicebruker.brukernavn: se-vault
farskapsportal-api.servicebruker.passord: se-vault

---
spring.profiles: integration-test

no.nav.security.jwt:
  issuer.selvbetjening :
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

urls:
  pdl-api:
    base-url: https://api-gw-q1.oera.no
  sts:
    base-url: https://api-gw-q1.oera.no

