spring.devtools.add-properties: false

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator
  endpoint.health.show-details: always

urls:
  apigw: ${APIGW_URL}
  pdl-api:
    graphql-endpoint: ${pdl_api_endpoint"}
  sts:
    security-token-service-endpoint: ${security_token_service_endpoint}

farskapsportal-api.servicebruker.brukernavn: srvfarskapsportal
farskapsportal-api.servicebruker.passord: ${srvfarskapsportal-pwd}

---
spring.profiles: test, local

PDL_API_BASE_URL: http://localhost:8096
STS_BASE_URL: http://localhost:8096


---
spring.profiles: live

no.nav.security.jwt:
    issuer.isso:
      discoveryurl: https://login.microsoftonline.com/NAVQ.onmicrosoft.com/.well-known/openid-configuration
      accepted_audience: 38e07d31-659d-4595-939a-f18dce3446c5
      cookiename: isso-idtoken
      #proxyurl: http://webproxy.nais:8088

---
########## Mock props ##########
spring.profiles: test, local

no.nav.security.jwt:
  issuers: isso
  issuer.isso:
    discoveryurl: http://metadata
    acceptedaudience: aud-localhost
    cookie_name: localhost-idtoken

farskapsportal-api.servicebruker.brukernavn: se-vault
farskapsportal-api.servicebruker.passord: se-vault


