apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    team: farskapsportal
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress }}
  envFrom:
    - secret: farskapsportal-api-secret
    - configmap: loginservice-idporten
  env:
    - name: APIGW_URL
      value: {{ api_gateway_url }}
    - name: DISCOVERY_URL
      value: {{ discovery_url }}
    - name: AUD_FP
      value: {{ aud }}
    - name: JDBC_URL
      value: {{ jdbc_url }}
  gcp:
    sqlInstances:
      - instance: FP
        type: POSTGRES_11
        databases:
          - name: fpdb
            envVarPrefix: DB
          - name: fpdb_main
            envVarPrefix: DB_MAIN
  accesspolicy:
    inbound:
      rules:
        - application: {{ allow_inbound_apps }}
    outbound:
      external:
        - host: api-gw-q1.oera.no
        - host: login.microsoftonline.com
