apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    team: farskapsportal
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress }}
  envFrom:
    - secret: farskapsportal-api-secret
    - configmap: loginservice-idporten
  env:
    - name: APIGW_URL
      value: {{ api_gateway_url }}
    - name: DISCOVERY_URL
      value: {{ discovery_url }}
    - name: AUD_FP
      value: {{ aud }}
    - name: BRUKERNOTIFIKASJONER_PAA
      value: "true"
    - name: VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID
      value: virksomhetssertifikat-prod
    - name: ESIGNERING_SUKSESS_URL
      value: {{ posten_esignering_suksess_url }}
    - name: ESIGNERING_AVBRUTT_URL
      value: {{ posten_esignering_avbrutt_url }}
    - name: ESIGNERING_FEILET_URL
      value: {{ posten_esignering_feilet_url }}
    - name: FARSKAPSPORTAL_URL
      value: https://farskapsportal.adeo.no
    - name: KAFKA_BROKERS
      value: SASL_SSL://a01apvl00145.adeo.no:SASL_SSL://8443,a01apvl00146.adeo.no:SASL_SSL://8443,a01apvl00147.adeo.no:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL_CONFIG
      value: https://kafka-schema-registry.nais.adeo.no
    - name: SKATT_URL
      value: {{ skatt_url }}
  gcp:
    sqlInstances:
      - name: fp
        type: POSTGRES_12
        databases:
          - name: fpdb
            envVarPrefix: DB
    outbound:
      external:
        - host: api.signering.posten.no
        - host: folkeregisteret-api-ekstern.sits.no
        - host: secretmanager.googleapis.com
