apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - {{ ingress }}
  env:
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  envFrom:
  {{#each secret}}
    - secret: {{this.name } }
  {{/each}}
  accessPolicy:
    outbound:
      external:
        - host: api.signering.posten.no
        - host: folkeregisteret.api.skatteetaten.no
        - host: secretmanager.googleapis.com
