apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  image: {{ image }}
  kafka:
    pool: nav-prod
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
  ingresses:
    - {{ ingress }}
  env:
    - name: APPNAVN
      value: {{ name }}
    - name: SPRING_PROFILES_ACTIVE
      value: live, nais
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  envFrom:
  {{#each secret}}
    - secret: {{this.name}}
  {{/each}}
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: api-gw.oera.no
        - host: api.signering.posten.no
        - host: folkeregisteret.api.skatteetaten.no
        - host: oppgave.prod-fss-pub.nais.io
        - host: secretmanager.googleapis.com
      rules:
        - application: farskapsportal-api