apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - {{ ingress }}
  env:
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  envFrom:
  {{#each secret}}
    - secret: {{this.name}}
  {{/each}}
    - configmap: loginservice-idporten
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - name: {{ gcp.sql-instances.name }}
        tier: {{ gcp.sql-instances.tier }}
        type: {{ gcp.sql-instances.type }}
        databases:
          - name: {{ gcp.sql-instances.databases.name }}
            envVarPrefix: {{ gcp.sql-instances.databases.env-var-prefix }}
            users:
              - name: {{ gcp.sql-instances.databases.users.asynkron.name }}
  accessPolicy:
    outbound:
      external:
        - host: api.difitest.signering.posten.no
        - host: folkeregisteret-api-ekstern.sits.no
        - host: secretmanager.googleapis.com
