name: farskapsportal-api
ingress: https://farskapsportal-api.intern.nav.no
gcp:
  secretmanager.host: secretmanager.googleapis.com
  sql-instances:
    diskSize: 505
    name: fp-prod
    tier: db-custom-1-3840
    type: POSTGRES_12
    databases:
      name: fpdb-prod
      env-var-prefix: DB
      users:
        asynkron:
          name: asynkron_prod
env:
  - name: APIGW_URL
    value: https://api-gw.oera.no
  - name: BRUKERNOTIFIKASJON_PAA
    value: "true"
  - name: DB_USER_ASYNKRON
    value: asynkron_prod
  - name: POSTGRES_CONNECTION_NAME
    value: farskapsportal-prod-f231:europe-north1:fp-prod
  - name: VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID
    value: "642182003125"
  - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_NAVN
    value: virksomhetssertifikat-farskap-keystore-jceks_2021-2024
  - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_VERSJON
    value: "3"
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_PROSJEKT_ID
    value: "642182003125"
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_HEMMELIGHET_NAVN
    value: farskap-keystore-credentials-json
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_HEMMELIGHET_VERSJON
    value: "3"
  - name: ESIGNERING_SUKSESS_URL
    value: https://farskapsportal.nav.no/suksess
  - name: ESIGNERING_AVBRUTT_URL
    value: https://farskapsportal.nav.no/avbrutt
  - name: ESIGNERING_FEILET_URL
    value: https://farskapsportal.nav.no/avbrutt
  - name: FARSKAPSPORTAL_URL
    value: https://farskapsportal.nav.no
  - name: INTEGRATION_TEST_CONTROLLER_PAA
    value: "false"
  - name: SKATT_URL
    value: https://folkeregisteret.api.skatteetaten.no
