name: Deploy api-alerts to dev-gcp
on:
  push:
    branches:
      - '**'
      - '!release'
    paths:
      - '.nais/alert/alerts-dev.yml'
      - '**/api-alerts-dev-deploy.yml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploy alerts to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/alert/alerts-dev.yml
