name: release farskapsportal-api
on:
  push:
    branches:
      - release
    paths:
      - 'pom.xml'
      - 'apps/api/**'
      - 'libs/**'
      - '.nais/app/**'
      - '**/api-ci.yml'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ghcr.io/${{ github.repository }}/farskapsportal-api:${{ github.sha }}

jobs:
  verify:
    name: Verify that release commit is present in main branch
    runs-on: ubuntu-latest

    steps:
      - run: git clone --bare https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/${{ github.repository }}
      - name: check if commit to build exists in main branch
        run: |
          cd $( echo ${{ github.repository }} | sed 's;navikt/;;' ).git
          git log | grep -c ${{ github.sha }}
  build:
    name: Build release with maven and docker
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B -e --settings .m2/maven-settings.xml clean install
      - name: Build and publish Docker image
        run: |
          docker build --tag ${IMAGE} --build-arg JAR_PATH=apps/api/target/app.jar .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/.nais/app/naiserator-prod.yml
          VARS: deploy/.nais/app/prod.yml

