name: continuous integration farskapsportal-api
on:
  push:
    branches:
      - '**'
      - '!release'
    paths:
      - 'pom.xml'
      - 'apps/api/**'
      - 'libs/**'
      - '.nais/app/**'
      - '**/api-ci.yml'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ghcr.io/${{ github.repository }}/farskapsportal-api:${{ github.sha }}

jobs:
  build:
    name: Build with maven and docker
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B -e --no-transfer-progress package --settings .m2/maven-settings.xml clean install --file pom.xml
      - name: Build and publish Docker image
        run: |
          docker build --tag ${IMAGE} --build-arg JAR_PATH=apps/api/target/app.jar --build-arg JAVA_OPTS=-Djavax.net.debug=handshake .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}


  style:
    name: 📝 Sjekk kodestil
    runs-on: ubuntu-latest

    steps:
      - name: Reset working directory
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: GIT checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Valider Java-formatering
        run: |
          mvn fmt:check --settings .m2/maven-settings.xml
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    needs: build

    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy
      - name: Deploy main to dev-gcp
        if: github.ref == 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/app/naiserator-dev.yml
          VARS: deploy/.nais/app/main.yml
      - name: Deploy feature to dev-gcp
        if: github.ref != 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/app/naiserator-dev.yml
          VARS: deploy/.nais/app/feature.yml
