on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-git/tag-snap@v1-tag-snap
