on:
  push:
    branches:
      - 'release'
    paths:
      - 'apps/api/**'
      - '.nais/apps/api/**'
      - '**/api-ci.yml'

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Tag latest deploy to prod
    needs: deploy

    steps:
      - uses: actions/checkout@v3
      - uses: navikt/bidrag-git/tag@v1-tag
